version: "3.4"

services:
  app:
    container_name: app
    build: .
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    restart: always

  celery_worker:
    container_name: celery_worker
    build: .
    command: celery -A celery_worker.celery worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@127.0.0.1:5672//
      - CELERY_RESULT_BACKEND=redis://localhost:6379/0

  rabbitmq:
    container_name: rabbitmq
    image: "bitnami/rabbitmq:3.7"
    ports:
      - "4369:4369"
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"
    volumes:
      - "rabbitmq_data:/bitnami"

  redis:
    container_name: redis
    image: "bitnami/redis:5.0.4"
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/bitnami/redis/data"

volumes:
  rabbitmq_data:
    driver: local
  redis_data:
    driver: local